import 'dart:convert';
import 'dart:io';

/// Quick migrator: converts common plain-math patterns in quiz bank text to
/// inline LaTeX and emits SQL UPDATE statements.
///
/// Usage:
/// dart run tool/convert_quiz_bank_to_latex.dart \
///   docs/quiz_question_template_in_Supabase.csv \
///   docs/generated_quiz_latex_migration.sql
void main(List<String> args) async {
  final inputPath = args.isNotEmpty
      ? args[0]
      : 'docs/quiz_question_template_in_Supabase.csv';
  final outputPath = args.length > 1
      ? args[1]
      : 'docs/generated_quiz_latex_migration.sql';

  final inputFile = File(inputPath);
  if (!inputFile.existsSync()) {
    stderr.writeln('Input file not found: $inputPath');
    exitCode = 1;
    return;
  }

  final csvText = await inputFile.readAsString();
  final csvRows = _parseCsv(csvText);

  if (csvRows.length < 2) {
    stderr.writeln('CSV does not contain data rows.');
    exitCode = 1;
    return;
  }

  final headers = csvRows.first;
  final updates = <String>[];
  var changedRows = 0;

  for (final row in csvRows.skip(1)) {
    if (row.every((field) => field.trim().isEmpty)) {
      continue;
    }

    final paddedRow = _padRow(row, headers.length);
    final record = <String, String>{};
    for (var i = 0; i < headers.length; i++) {
      record[headers[i]] = paddedRow[i];
    }

    final id = (record['id'] ?? '').trim();
    if (id.isEmpty) {
      continue;
    }

    final originalContent = record['content'] ?? '';
    final transformedContent = _convertTextWithInlineLatex(originalContent);

    final originalPayload = _decodeJsonMap(record['payload'] ?? '{}');
    final transformedPayload = _transformPayload(originalPayload);

    final originalMetadata = _decodeJsonMap(record['metadata'] ?? '{}');
    final transformedMetadata = _transformMetadata(originalMetadata);

    final assignments = <String>[];

    if (transformedContent != originalContent) {
      assignments.add("content = '${_escapeSql(transformedContent)}'");
    }

    final originalPayloadJson = jsonEncode(originalPayload);
    final transformedPayloadJson = jsonEncode(transformedPayload);
    if (originalPayloadJson != transformedPayloadJson) {
      assignments.add(
        "payload = '${_escapeSql(transformedPayloadJson)}'::jsonb",
      );
    }

    final originalMetadataJson = jsonEncode(originalMetadata);
    final transformedMetadataJson = jsonEncode(transformedMetadata);
    if (originalMetadataJson != transformedMetadataJson) {
      assignments.add(
        "metadata = '${_escapeSql(transformedMetadataJson)}'::jsonb",
      );
    }

    if (assignments.isEmpty) {
      continue;
    }

    changedRows += 1;
    updates.add(
      "UPDATE quiz_question_template SET ${assignments.join(', ')} WHERE id = '${_escapeSql(id)}';",
    );
  }

  final outputBuffer = StringBuffer()
    ..writeln('-- Auto-generated by tool/convert_quiz_bank_to_latex.dart')
    ..writeln('-- Source: $inputPath')
    ..writeln('-- Changed rows: $changedRows')
    ..writeln('-- Generated at: ${DateTime.now().toIso8601String()}')
    ..writeln()
    ..writeln('BEGIN;')
    ..writeln();

  if (updates.isEmpty) {
    outputBuffer.writeln('-- No changes detected.');
  } else {
    for (final update in updates) {
      outputBuffer.writeln(update);
    }
  }

  outputBuffer
    ..writeln()
    ..writeln('COMMIT;')
    ..writeln();

  final outputFile = File(outputPath);
  outputFile.createSync(recursive: true);
  await outputFile.writeAsString(outputBuffer.toString());

  stdout.writeln('Done. Wrote $changedRows UPDATE statements to $outputPath');
}

List<List<String>> _parseCsv(String text) {
  final rows = <List<String>>[];
  final row = <String>[];
  final field = StringBuffer();
  var inQuotes = false;

  for (var i = 0; i < text.length; i++) {
    final char = text[i];

    if (inQuotes) {
      if (char == '"') {
        final nextIsQuote = i + 1 < text.length && text[i + 1] == '"';
        if (nextIsQuote) {
          field.write('"');
          i += 1;
        } else {
          inQuotes = false;
        }
      } else {
        field.write(char);
      }
      continue;
    }

    if (char == '"') {
      inQuotes = true;
      continue;
    }

    if (char == ',') {
      row.add(field.toString());
      field.clear();
      continue;
    }

    if (char == '\n') {
      row.add(field.toString());
      field.clear();
      rows.add(List<String>.from(row));
      row.clear();
      continue;
    }

    if (char == '\r') {
      continue;
    }

    field.write(char);
  }

  if (field.isNotEmpty || row.isNotEmpty) {
    row.add(field.toString());
    rows.add(List<String>.from(row));
  }

  return rows;
}

List<String> _padRow(List<String> row, int targetLength) {
  if (row.length >= targetLength) {
    return row.sublist(0, targetLength);
  }

  return <String>[
    ...row,
    ...List<String>.filled(targetLength - row.length, ''),
  ];
}

Map<String, dynamic> _decodeJsonMap(String raw) {
  final trimmed = raw.trim();
  if (trimmed.isEmpty) {
    return <String, dynamic>{};
  }

  try {
    final decoded = jsonDecode(trimmed);
    if (decoded is Map<String, dynamic>) {
      return decoded;
    }
    if (decoded is Map) {
      return Map<String, dynamic>.from(decoded);
    }
  } catch (_) {
    // Keep original value when malformed.
  }

  return <String, dynamic>{};
}

Map<String, dynamic> _transformPayload(Map<String, dynamic> payload) {
  dynamic transform(dynamic value, {required String keyHint}) {
    if (value is Map) {
      final result = <String, dynamic>{};
      for (final entry in value.entries) {
        final key = entry.key.toString();
        result[key] = transform(entry.value, keyHint: key);
      }
      return result;
    }

    if (value is List) {
      return value
          .map((item) => transform(item, keyHint: keyHint))
          .toList(growable: false);
    }

    if (value is String) {
      if (_isFormulaField(keyHint)) {
        return _toLatexExpression(value);
      }

      if (_isMathTextField(keyHint)) {
        return _convertTextWithInlineLatex(value);
      }
    }

    return value;
  }

  return transform(payload, keyHint: 'payload') as Map<String, dynamic>;
}

Map<String, dynamic> _transformMetadata(Map<String, dynamic> metadata) {
  dynamic transform(dynamic value, {required String keyHint}) {
    if (value is Map) {
      final result = <String, dynamic>{};
      for (final entry in value.entries) {
        final key = entry.key.toString();
        result[key] = transform(entry.value, keyHint: key);
      }
      return result;
    }

    if (value is List) {
      return value
          .map((item) => transform(item, keyHint: keyHint))
          .toList(growable: false);
    }

    if (value is String && _isFormulaField(keyHint)) {
      return _toLatexExpression(value);
    }

    return value;
  }

  return transform(metadata, keyHint: 'metadata') as Map<String, dynamic>;
}

bool _isFormulaField(String key) {
  final normalized = key.toLowerCase();
  return normalized == 'formula' ||
      normalized.endsWith('_formula') ||
      normalized == 'latex';
}

bool _isMathTextField(String key) {
  final normalized = key.toLowerCase();
  return normalized == 'content' ||
      normalized == 'text' ||
      normalized == 'explanation' ||
      normalized == 'general_hint' ||
      normalized == 'hint' ||
      normalized == 'statement';
}

String _convertTextWithInlineLatex(String source) {
  if (source.trim().isEmpty) {
    return source;
  }

  var output = source;
  output = _applyOutsideInlineLatex(
    output,
    (segment) => _wrapPatternMatches(segment, _sqrtPattern),
  );
  output = _applyOutsideInlineLatex(
    output,
    (segment) => _wrapPatternMatches(segment, _numericPowerPattern),
  );
  output = _applyOutsideInlineLatex(
    output,
    (segment) => _wrapPatternMatches(segment, _powerTermPattern),
  );
  output = _applyOutsideInlineLatex(
    output,
    (segment) => _wrapPatternMatches(segment, _derivativePattern),
  );

  return _normalizeInlineLatexSpacing(output);
}

String _normalizeInlineLatexSpacing(String source) {
  return _mergeAdjacentInlineLatex(
    source,
  ).replaceAll(RegExp(r'\s{2,}'), ' ').trim();
}

String _mergeAdjacentInlineLatex(String source) {
  var output = source;

  while (true) {
    final merged = output.replaceAllMapped(
      RegExp(r'\$([^$]+)\$\$([^$]+)\$'),
      (match) => r'$' + (match.group(1) ?? '') + (match.group(2) ?? '') + r'$',
    );

    if (merged == output) {
      return merged;
    }

    output = merged;
  }
}

String _applyOutsideInlineLatex(
  String input,
  String Function(String segment) transformer,
) {
  final matches = RegExp(r'\$[^$]*\$').allMatches(input).toList();
  if (matches.isEmpty) {
    return transformer(input);
  }

  final buffer = StringBuffer();
  var cursor = 0;

  for (final match in matches) {
    if (match.start > cursor) {
      buffer.write(transformer(input.substring(cursor, match.start)));
    }

    buffer.write(match.group(0));
    cursor = match.end;
  }

  if (cursor < input.length) {
    buffer.write(transformer(input.substring(cursor)));
  }

  return buffer.toString();
}

String _wrapPatternMatches(String segment, RegExp pattern) {
  final matches = pattern.allMatches(segment).toList();
  if (matches.isEmpty) {
    return segment;
  }

  final buffer = StringBuffer();
  var cursor = 0;

  for (final match in matches) {
    if (match.start > cursor) {
      buffer.write(segment.substring(cursor, match.start));
    }

    final token = match.group(0)?.trim() ?? '';
    if (token.isEmpty) {
      cursor = match.end;
      continue;
    }

    final latex = _toLatexExpression(token);
    buffer
      ..write(r'$')
      ..write(latex)
      ..write(r'$');

    cursor = match.end;
  }

  if (cursor < segment.length) {
    buffer.write(segment.substring(cursor));
  }

  return buffer.toString();
}

String _toLatexExpression(String source) {
  var output = source.trim();

  if (output.startsWith(r'$') && output.endsWith(r'$') && output.length > 2) {
    output = output.substring(1, output.length - 1);
  }

  output = _normalizeUnicodeSquareRoot(output);
  output = _normalizeSuperscriptSequences(output);

  output = output
      .replaceAll('−', '-')
      .replaceAll('<=', r'\leq ')
      .replaceAll('>=', r'\geq ')
      .replaceAll('×', r'\times ')
      .replaceAll('·', r'\cdot ')
      .replaceAll('*', r' \cdot ')
      .replaceAll('π', r'\pi ')
      .replaceAll('²', '^{2}')
      .replaceAll('³', '^{3}')
      .replaceAll('⁴', '^{4}')
      .replaceAll('⁵', '^{5}')
      .replaceAll('⁶', '^{6}')
      .replaceAll('⁷', '^{7}')
      .replaceAll('⁸', '^{8}')
      .replaceAll('⁹', '^{9}')
      .replaceAll('⁰', '^{0}')
      .replaceAll('₀', '_{0}')
      .replaceAll('₁', '_{1}')
      .replaceAll('₂', '_{2}')
      .replaceAll('₃', '_{3}')
      .replaceAll('₄', '_{4}')
      .replaceAll('₅', '_{5}')
      .replaceAll('₆', '_{6}')
      .replaceAll('₇', '_{7}')
      .replaceAll('₈', '_{8}')
      .replaceAll('₉', '_{9}');

  output = output.replaceAllMapped(
    RegExp(r'\^([0-9]+)'),
    (match) => '^{${match.group(1)}}',
  );

  output = _convertSqrtToLatex(output);
  output = output.replaceAll(RegExp(r'\s{2,}'), ' ').trim();

  return output;
}

String _normalizeSuperscriptSequences(String source) {
  return source.replaceAllMapped(
    RegExp(r'([A-Za-z0-9π\)\}])([⁰¹²³⁴⁵⁶⁷⁸⁹⁺⁻⁼⁽⁾ˣʸᵗᵃᵇᶜᵈᵉᶠᵍʰⁱʲᵏˡᵐᵒᵖʳˢᵘᵛʷᶻⁿ]+)'),
    (match) {
      final base = match.group(1) ?? '';
      final superscriptRaw = match.group(2) ?? '';
      final exponent = _normalizeExponentFragment(
        superscriptRaw
            .split('')
            .map((char) => _superscriptCharMap[char] ?? char)
            .join(),
      );
      return '$base^{$exponent}';
    },
  );
}

String _normalizeExponentFragment(String source) {
  var output = source.replaceAll(RegExp(r'\s+'), '');
  output = output.replaceAllMapped(
    RegExp(r'([A-Za-z])([0-9]+)'),
    (match) => '${match.group(1)}^{${match.group(2)}}',
  );
  return output;
}

String _normalizeUnicodeSquareRoot(String source) {
  var output = source.replaceAll('√(', 'sqrt(');
  output = output.replaceAllMapped(
    RegExp(r'√\s*([A-Za-z0-9π]+)'),
    (match) => 'sqrt(${match.group(1)})',
  );
  return output;
}

String _convertSqrtToLatex(String input) {
  final buffer = StringBuffer();
  var index = 0;

  while (index < input.length) {
    final sqrtIndex = input.indexOf('sqrt(', index);
    if (sqrtIndex == -1) {
      buffer.write(input.substring(index));
      break;
    }

    buffer.write(input.substring(index, sqrtIndex));

    final expressionStart = sqrtIndex + 5;
    var depth = 1;
    var cursor = expressionStart;

    while (cursor < input.length && depth > 0) {
      final char = input[cursor];
      if (char == '(') {
        depth += 1;
      } else if (char == ')') {
        depth -= 1;
      }
      cursor += 1;
    }

    if (depth == 0) {
      final inner = input.substring(expressionStart, cursor - 1);
      buffer
        ..write(r'\sqrt{')
        ..write(_convertSqrtToLatex(inner))
        ..write('}');
      index = cursor;
    } else {
      final rest = input.substring(expressionStart);
      buffer
        ..write(r'\sqrt{')
        ..write(rest)
        ..write('}');
      index = input.length;
    }
  }

  return buffer.toString();
}

String _escapeSql(String value) {
  return value.replaceAll("'", "''");
}

final RegExp _sqrtPattern = RegExp(
  r'(?<![A-Za-zÀ-ỹ])sqrt\([^()]+\)(?![A-Za-zÀ-ỹ])',
  caseSensitive: false,
);

final RegExp _numericPowerPattern = RegExp(
  r'(?<![0-9/])(?:\d+(?:\.\d+)?)(?:\^[-+]?\d+|[⁰¹²³⁴⁵⁶⁷⁸⁹⁺⁻⁼⁽⁾ˣʸᵗᵃᵇᶜᵈᵉᶠᵍʰⁱʲᵏˡᵐᵒᵖʳˢᵘᵛʷᶻⁿ])+',
  caseSensitive: false,
);

final RegExp _powerTermPattern = RegExp(
  r'(?<![0-9/])(?:\d+(?:\.\d+)?)?[A-Za-zπ](?:\^[-+]?\d+|[⁰¹²³⁴⁵⁶⁷⁸⁹⁺⁻⁼⁽⁾ˣʸᵗᵃᵇᶜᵈᵉᶠᵍʰⁱʲᵏˡᵐᵒᵖʳˢᵘᵛʷᶻⁿ])+',
  caseSensitive: false,
);

final RegExp _derivativePattern = RegExp(
  r"(?<![A-Za-zÀ-ỹ0-9])(?:[fgyvsatx]\([^)]*\)'|[fgyvsatx]')",
  caseSensitive: false,
);

const Map<String, String> _superscriptCharMap = {
  '⁰': '0',
  '¹': '1',
  '²': '2',
  '³': '3',
  '⁴': '4',
  '⁵': '5',
  '⁶': '6',
  '⁷': '7',
  '⁸': '8',
  '⁹': '9',
  '⁺': '+',
  '⁻': '-',
  '⁼': '=',
  '⁽': '(',
  '⁾': ')',
  'ˣ': 'x',
  'ʸ': 'y',
  'ᵗ': 't',
  'ᵃ': 'a',
  'ᵇ': 'b',
  'ᶜ': 'c',
  'ᵈ': 'd',
  'ᵉ': 'e',
  'ᶠ': 'f',
  'ᵍ': 'g',
  'ʰ': 'h',
  'ⁱ': 'i',
  'ʲ': 'j',
  'ᵏ': 'k',
  'ˡ': 'l',
  'ᵐ': 'm',
  'ᵒ': 'o',
  'ᵖ': 'p',
  'ʳ': 'r',
  'ˢ': 's',
  'ᵘ': 'u',
  'ᵛ': 'v',
  'ʷ': 'w',
  'ᶻ': 'z',
  'ⁿ': 'n',
};
